# Generated by Django 5.1.3 on 2025-01-28 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('cbo', models.AutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(max_length=100, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('id_tarefa_mail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'permissions': [('cadastrar_funcionarios', 'Pode cadastrar funcionários')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioBasico',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(help_text='Digite um nome de usuário com digitos e números.', max_length=150, unique=True, verbose_name='Usuário')),
                ('senha_usuario', models.CharField(max_length=128)),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('basico', 'Básico')], default='basico', max_length=50)),
                ('setor', models.CharField(max_length=100)),
                ('data_criarUsu', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
