# Generated by Django 5.1.3 on 2025-01-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobasico',
            name='senha_usuario',
        ),
    ]
