# Generated by Django 5.1.3 on 2024-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_cbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id_tarefa_mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
