# Generated by Django 5.1.3 on 2024-11-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_id_tarefa_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': [('importar_funcionarios', 'Pode importar funcionários')]},
        ),
    ]
