# Generated by Django 5.1.3 on 2025-01-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_funcionario_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': [('cadastrar_funcionarios', 'Pode cadastrar funcionários')]},
        ),
    ]
