# Generated by Django 5.1.3 on 2025-01-16 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha_usuario',
            field=models.CharField(help_text='Crie uma senha segura.', max_length=128, validators=[django.core.validators.RegexValidator(message='Este campo deve conter apenas letras e números.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
